//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_host
    {
        public int data_host_id { get; set; }
        public string host_name { get; set; }
        public string portal_url { get; set; }
        public Nullable<int> project_id { get; set; }
        public string description { get; set; }
    
        public virtual project project { get; set; }
    }
}
