//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_keywords
    {
        public int project_keywords_id { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> keyword_id { get; set; }
    
        public virtual project project { get; set; }
        public virtual keyword keyword { get; set; }
    }
}
