//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_monitor_coord
    {
        public int project_monitor_coord_id { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> monitoring_coordination_id { get; set; }
    
        public virtual monitoring_coordination monitoring_coordination { get; set; }
        public virtual project project { get; set; }
    }
}
