//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public site()
        {
            this.site_parameters = new HashSet<site_parameters>();
            this.site_media = new HashSet<site_media>();
            this.site_resource = new HashSet<site_resource>();
            this.site_frequency = new HashSet<site_frequency>();
        }
    
        public int site_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> project_id { get; set; }
        public string sample_platform { get; set; }
        public string additional_info { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public string waterbody { get; set; }
        public Nullable<int> status_type_id { get; set; }
        public Nullable<int> lake_type_id { get; set; }
        public string country { get; set; }
        public string state_province { get; set; }
        public string watershed_huc8 { get; set; }
        public string url { get; set; }
    
        public virtual status_type status_type { get; set; }
        public virtual lake_type lake_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<site_parameters> site_parameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<site_media> site_media { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<site_resource> site_resource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<site_frequency> site_frequency { get; set; }
        public virtual project project { get; set; }
    }
}
