//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_media
    {
        public int site_media_id { get; set; }
        public int site_id { get; set; }
        public int media_type_id { get; set; }
    
        public virtual media_type media_type { get; set; }
        public virtual site site { get; set; }
    }
}
